language: cpp
env:
  global:
    - DEPS="lcov"
matrix:
  include:
    - os: osx
      compiler: clang
      osx_image: xcode8.3
      env:
        - DEPS="${DEPS} llvm@3.7"
        - LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake/
    - os: osx
      compiler: clang
      osx_image: xcode8
      env:
        - DEPS="${DEPS} llvm@3.7"
        - LLVM_DIR=/usr/local/opt/llvm@3.7/lib/llvm-3.7/share/llvm/cmake/
    - os: linux
      compiler: g++
      root: required
      services:
        - docker
      env:
        - DIST=xenial

install:
  - if [ $TRAVIS_OS_NAME = osx   ]; then brew install ${DEPS}; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then cd docker/build &&  docker build . -f ./${DIST}.Dockerfile -t hobbes:build; cd -; fi

script:
  - if [ $TRAVIS_OS_NAME = osx   ]; then mkdir build && cd build/ && cmake .. && make && make test; fi
  - if [ $TRAVIS_OS_NAME = linux ]; then docker run -it -v ${PWD}:/src hobbes:build; fi

branches:
  only:
    - master
    - travis

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"